version: "3.4"

networks:
  default:

# TODO: simplify this config with anchors

services:
  api_v1:
    image: top30__api_v1
    container_name: TOP30__api_v1
    build:
      context: .
      dockerfile: deployment/api/Dockerfile
    volumes:
      - ./app:/opt/app
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env.docker
    depends_on:
      - postgres
  postgres:
    container_name: TOP30__postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: top
