"""

Revision ID: 143a2239daa5
Revises: 
Create Date: 2022-04-29 13:57:29.927318

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '143a2239daa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('name', sa.String(length=60), nullable=True),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('refresh_token', sa.Text(), nullable=True),
        sa.Column('password', sa.LargeBinary(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.CheckConstraint(
            'octet_length(password) BETWEEN 59 AND 60', name='password_simple_bcrypt_check'
        ),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('refresh_token'),
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
